version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./sql/InitSQL.sql:/docker-entrypoint-initdb.d/create_schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgadmin: